queue_rules:
  - name: main
    queue_conditions:
      - or:
          - author=dependabot[bot]
          - author=renovate[bot]
      - base=main
      - -label=do-not-merge
    autoqueue: true
    merge_method: squash
